blank_issues_enabled: false
contact_links:
  - name: P2 Forum Community Support
    url: https://forums.parallax.com/discussion/172288/p2-driver-for-hub75-led-matrix-panels#latest
    about: Discuss the P2 HUB75 LED Matrix Driver here.
